In [1]:
import pandas as pd
import os
from sksurgerynditracker.nditracker import NDITracker
import numpy as np

In [ ]:
"""
    Define the tool tip offset
    Using Medtronic Chiken Foot for Phantom Registration
    the tool tip offset value of Medtronic Chicken Foot is from Mike github repo
    Alternatively, the tool tip offset can be calculated by PIVOTING using NDI ToolBox Utilities
"""
TOOL_TIP_OFFSET = np.array([-304.5728,-0.3053,-0.1412, 1]) 

In [2]:
"""
    Initialize the NDI tracker
    MAKE SURE you have the Chicken Foot .rom file and its path
"""
SETTINGS = {
    "tracker type": "vega",
    "ip address": "169.254.7.250",
    "port": 8765,

    # Windows Path
    "romfiles": ["C:\\Users\\f007wsq\\Desktop\\tools_and_models\\tool_defs\\medtronic_chicken_foot_960_556.rom"]
}
tracker = NDITracker(SETTINGS)
tracker.start_tracking()

In [3]:
def get_tooltip_data(tool_tip_offset):
    port_handles, timestamps, framenumbers, tracking, quality = tracker.get_frame()
    tool_tip = np.dot(tracking[0], tool_tip_offset)
    x_pos = tool_tip[0]
    y_pos = tool_tip[1]
    z_pos = tool_tip[2]
    return x_pos, y_pos, z_pos

In [4]:
"""
    Load the Markers Locations on Phantom
    The locations here are in CT's coordinate system
    The locations can be obtained by loading the CT's .stl model into SLICER or directly getting from .stl model in Solidworks or similar software
"""
markers_fcsv_file = 'CT.fcsv'

# Windows Path
markers_CT = pd.read_csv("C:\\Users\\f007wsq\\Desktop\\tools_and_models\\slicer_files" + "\\"  + markers_fcsv_file, comment='#', header=None)

In [5]:
""""
    markers_PO saves the Marker Locations in Polaris coord system
    Use the chicken foot tool
    Point the tool tip at each marker and hit ENTER to collect the positions
"""
markers_PO = []
i = 0
while i < len(markers_CT):
    user_input = input("Press Enter to Collect Points：")
        
    if user_input.lower() == 'Exit':
        break

    if user_input == '':  # 如果按回车键
        x, y, z = get_tooltip_data(TOOL_TIP_OFFSET)  # 获取当前Polaris的位置
        if np.isnan(x) or np.isnan(y) or np.isnan(z):
            print("Collect again")
        else:
            markers_PO.append([x, y, z])  # 保存采集的数据       
            i = i + 1
            print(f"Collected Point: {i}")
            print(f"Position: {x, y, z}")
            

Collected Point: 1
Position: (np.float64(40.04906265535004), np.float64(-56.070647664221966), np.float64(-1445.8594203154883))
Collected Point: 2
Position: (np.float64(-19.445325992150003), np.float64(150.22359627637798), np.float64(-1451.607421728674))
Collected Point: 3
Position: (np.float64(-61.776361144728014), np.float64(47.940234749587994), np.float64(-1519.7714120940961))
Collected Point: 4
Position: (np.float64(-56.58441401261405), np.float64(49.795803678458), np.float64(-1626.251505732848))
Collected Point: 5
Position: (np.float64(1.1175919406480261), np.float64(143.290727190202), np.float64(-1674.176156837596))
Collect again
Collect again
Collect again
Collected Point: 6
Position: (np.float64(95.83956213392608), np.float64(-82.85855822543802), np.float64(-1662.8455113762502))


In [6]:
from scipy.spatial.transform import Rotation
def compute_rigid_transform(P_CT, P_PO):
    """
        Calculate the rigid transformation from CT or Phantom coord system to Polaris coord system, in other word,
        Express {CT} in {PO}, PO: short for Polaris,
        P_CT: ndarray (N,3), the markers 3D location in {CT}
        P_PO: ndarray (N,3), the markers 3D location in {PO}

        :return: R (3x3 rotation matrix), T (3x1 translation vector)
    """
    # 计算两个点集的质心
    centroid_CT = np.mean(P_CT, axis=0)
    centroid_PO = np.mean(P_PO, axis=0)

    # 去中心化（中心化点集）
    P_CT_centered = P_CT - centroid_CT
    P_PO_centered = P_PO - centroid_PO

    # 计算协方差矩阵 H
    H = P_CT_centered.T @ P_PO_centered

    # 进行 SVD 分解
    U, _, Vt = np.linalg.svd(H)
    
    # 计算旋转矩阵 R
    R = Vt.T @ U.T

    # 处理可能的反射问题（保证 R 是正交矩阵，det(R) = 1）
    if np.linalg.det(R) < 0:
        Vt[-1, :] *= -1
        R = Vt.T @ U.T

    # 计算平移向量 T
    T = centroid_PO - R @ centroid_CT

    return R, T

In [7]:
P_CT = []
markers_CT = np.array(markers_CT)
for i in range(len(markers_CT)):
    P_CT.append(markers_CT[i][1:4])
P_CT = np.array(P_CT, dtype=np.float64)
print(P_CT)

[[-108.610672    -93.25263214  128.33157349]
 [  98.98032379 -147.69650269  129.06384277]
 [  -0.64749622 -195.0091095   193.43154907]
 [   1.81817102 -195.08876038  301.2645874 ]
 [  98.23664093 -144.80683899  351.45755005]
 [-134.05921936  -50.59602356  351.95401001]]


In [8]:
P_PO = np.array(markers_PO, dtype=np.float64)
print(P_PO)

[[ 4.00490627e+01 -5.60706477e+01 -1.44585942e+03]
 [-1.94453260e+01  1.50223596e+02 -1.45160742e+03]
 [-6.17763611e+01  4.79402347e+01 -1.51977141e+03]
 [-5.65844140e+01  4.97958037e+01 -1.62625151e+03]
 [ 1.11759194e+00  1.43290727e+02 -1.67417616e+03]
 [ 9.58395621e+01 -8.28585582e+01 -1.66284551e+03]]


In [9]:
"""
    Calculate the Rotation and Translation
"""
R, T = compute_rigid_transform(P_CT, P_PO)

In [10]:
def create_transformation_matrix(R, T):
    """
        Combine the Rotation and Translation into 4 x 4 Transformation Matrix
    """
    transformation_matrix = np.eye(4)  # 创建一个 4x4 单位矩阵
    transformation_matrix[:3, :3] = R  # 设置旋转部分
    transformation_matrix[:3, 3] = T.flatten()  # 设置平移部分
    return transformation_matrix

In [11]:
"""
    Here we have the transformation,
    Express {CT} in {PO}
    By applying the Transformation, we can have the CT model/Phantom in Polaris Coordinate System
"""
transformation_matrix = create_transformation_matrix(R, T)
print(transformation_matrix)

[[-1.78752390e-02  9.97490742e-01  6.85032455e-02  1.20512994e+02]
 [ 9.99681492e-01  1.90512108e-02 -1.65519287e-02  5.60709263e+01]
 [-1.78154654e-02  6.81855570e-02 -9.97513578e-01 -1.31217738e+03]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
